### PR TITLE
Added  Simon's greeting

### PR DESCRIPTION
**Pull request by simonhm31**
I added a greeting for Simon

### CODE REVIEW

**Review by KenBroden — DISMISSED** [review]
Looks good

**Review by TristanKalvoda — DISMISSED** [review]
Nice work!

**Comment by ethangraybar** [comment]
Looks good!

**Review by NicMcPhee — DISMISSED** [review]

**Review by NicMcPhee — DISMISSED** [review]

**Review by mahon479 — DISMISSED** [review]
Looks good

**Review by NicMcPhee — APPROVED** [review]

**Review by KenBroden — APPROVED** [review]

**Pull request merged**
