### PR TITLE
Tristan's Greeting

### PR DESCRIPTION
**Pull request by TristanKalvoda**
I added a Greeting from Tristan

### CODE REVIEW

**Review by NicMcPhee — DISMISSED** [review]
Thanks!

**Review by TyBeas — DISMISSED** [review]
Looks good!

**Review by ethangraybar — DISMISSED** [review]
Looks good to me!

**Review by NicMcPhee — DISMISSED** [review]

**Review by NicMcPhee — APPROVED** [review]
Sorry for messing this up in class; hopefully this makes things better.

**Review by AndrewLam288 — APPROVED** [review]
Looks good.

**Pull request merged**
