### PR TITLE
Updated Hellos to include Ken message

### PR DESCRIPTION
**Pull request by KenBroden**
I added a greeting for Ken in Hello.java

### CODE REVIEW

**Review by NicMcPhee — DISMISSED** [review]
Thanks!

**Review by TristanKalvoda — DISMISSED** [review]
I approve this code

**Review by NicMcPhee — DISMISSED** [review]

**Review by AndrewLam288 — DISMISSED** [review]
Looks great.

**Review by NicMcPhee — APPROVED** [review]

**Review by TyBeas — APPROVED** [review]

**Review by jmahoney5 — APPROVED** [review]
Looks Good

**Pull request merged**
